<form role="form" method="post" action="./api/authority/">
    <div class="form-group">
        <label for="email">Email</label>
        <input class="form-control" type="email" name="email" required placeholder="Email Address"/>        
        <p class="help-block">
            A valid email address is required to sign in.
        </p>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" type="password" name="password" required placeholder="Your Password"/>
        <p class="help-block">
            Enter your password
        </p>
    </div>
    <div class="form-group pull-right">
        <button id="cancel" type="button" class="btn btn-inverse">Cancel</button>
        <button type="submit" class="btn btn-inverse">Sign In</button>
    </div>
    <script>
        $("#cancel").click(function() {document.location = document.location;});
    </script>    
</form>