<!DOCTYPE html>
<html lang="en-us">
	<head>
		<!-- %name% version %version% -->
		<!-- Created By %author% -->
		<meta name="description" content="Created by %name% v%version%">
		<meta name="keywords" content="%name% v%version%">
		<meta name="author" content="%name% - %author%">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="UTF-8">
		%header%
	</head>
	<body>
		%body%
	</body>
</html>